---
# Source: demo-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/instance: demo-app
    app.kubernetes.io/version: "0.1.0"
  namespace: helloworldwebapp-staging
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/instance: demo-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      name: http

---
# Source: demo-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/instance: demo-app
    app.kubernetes.io/version: "0.1.0"
  namespace: helloworldwebapp-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
      app.kubernetes.io/instance: demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-app
        app.kubernetes.io/instance: demo-app
    spec:
      securityContext:
        {}

      containers:
        - name: demo-app
          securityContext:
            {}

          image: catalinmoldovan/demo-cicd:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8090
              path: /actuator/health
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              port: 8090
              path: /actuator/info
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
          resources:
            {}
